<?php /* Smarty version 4.1.1, created on 2022-12-21 15:47:50
         compiled from 'E:\xampp\htdocs\smartwork\apps\diagram\language\fr\lang.txt' */ ?>
<?php
/* Smarty version 4.1.1, created on 2022-12-21 15:47:50
  from 'E:\xampp\htdocs\smartwork\apps\diagram\language\fr\lang.txt' */

/* @var Smarty_Internal_Template $_smarty_tpl */
if ($_smarty_tpl->_decodeProperties($_smarty_tpl, array (
  'version' => '4.1.1',
  'unifunc' => 'content_63a31c96856712_99258693',
  'has_nocache_code' => false,
  'file_dependency' => 
  array (
    '7520f7b4f2c6d20c8298932d91e021d395d02dcb' => 
    array (
      0 => 'E:\\xampp\\htdocs\\smartwork\\apps\\diagram\\language\\fr\\lang.txt',
      1 => 1662178516,
      2 => 'file',
    ),
  ),
  'includes' => 
  array (
  ),
),false)) {
function content_63a31c96856712_99258693 (Smarty_Internal_Template $_smarty_tpl) {
$_smarty_tpl->smarty->ext->configLoad->_loadConfigVars($_smarty_tpl, array (
  'sections' => 
  array (
    'contents' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Contenus',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'Libellé',
        'header_list_1' => 'Code',
        'header_list_2' => 'Libellé',
        'filter_list_reference' => 'Code : ',
        'filter_list_title' => 'Libellé : ',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' contenus trouvés',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression du contenu',
        'Lbl_delete' => 'Voulez-vous supprimer ce contenu ?',
        'Title_crud_edit' => 'Modification du contenu : ',
        'Title_crud_new' => 'Création d\'une nouveau contenu',
        'Lbl_contents_title' => 'Titre :',
        'Lbl_contents_reference' => 'Code :',
        'Lbl_contents_info' => 'Info',
        'Lbl_contents_image' => 'Image :',
        'Lbl_contents_description' => 'Description :',
        'Lbl_contents_comp' => 'Complément',
        'Lbl_contents_comp_image' => 'Image :',
        'Lbl_contents_comp_description' => 'Description :',
      ),
    ),
    'domains' => 
    array (
      'vars' => 
      array (
        'Title_select_domain' => 'Choisissez un domaine',
        'Title_list' => 'Domaines',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'Nom',
        'header_list_1' => 'Id',
        'header_list_2' => 'Nom',
        'header_list_3' => 'Libellé',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' domaines trouvés',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression du domaine',
        'Lbl_delete' => 'Voulez-vous supprimer ce domaine ?',
        'Title_crud_edit' => 'Modification du domaine : ',
        'Title_crud_new' => 'Création d\'un nouveau domaine',
        'Lbl_domains_name' => 'Nom :',
        'Lbl_domains_label' => 'Libellé :',
      ),
    ),
    'diagramtypes' => 
    array (
      'vars' => 
      array (
        'Title_list' => '\'Types d\'arborescence\'',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'Code',
        'header_list_1' => 'Code',
        'header_list_2' => 'Libellé',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' types trouvés',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression du type d\'arborescence',
        'Lbl_delete' => 'Voulez-vous supprimer ce type d\'arborescence ?',
        'Title_crud_edit' => 'Modification du type d\'arborescence : ',
        'Title_crud_new' => 'Création d\'un nouveau type d\'arborescence',
        'Lbl_diagramtypes_code' => 'Code :',
        'Lbl_diagramtypes_label' => 'Libellé :',
      ),
    ),
    'diagrams' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Arborescences',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'Nom',
        'header_list_1' => 'Id',
        'header_list_2' => 'Nom',
        'header_list_3' => 'Type',
        'header_list_4' => 'Libellé',
        'filter_list_type_id' => 'Type : ',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' arborescences trouvées',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression de l\'arborescence',
        'Lbl_delete' => 'Voulez-vous supprimer cette arborescence ?',
        'Bt_list_event' => 'Design',
        'Title_tool' => 'Copie de l\'arborescence',
        'Lbl_tool' => 'Voulez-vous copier cette arborescence ?',
        'Bt_list_tool' => 'Copier',
        'Title_crud_edit' => 'Modification de l\'arborescence : ',
        'Title_crud_new' => 'Création d\'un nouvelle arborescence',
        'Lbl_diagrams_name' => 'Nom :',
        'Lbl_diagrams_type_id' => 'Type :',
        'Lbl_diagrams_node_title' => 'Noeud racine :',
        'Lbl_diagrams_label' => 'Libellé :',
        'Lbl_diagrams_info' => 'Description',
        'Lbl_diagrams_nodes' => 'Noeuds',
        'Lbl_diagrams_links' => 'Liens',
      ),
    ),
    'notices' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Notices',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'Libellé',
        'header_list_1' => 'Code',
        'header_list_2' => 'Libellé',
        'filter_list_reference' => 'Code : ',
        'filter_list_label' => 'Libellé : ',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' notices trouvées',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression de la notice',
        'Lbl_delete' => 'Voulez-vous supprimer cette notice ?',
        'Title_crud_edit' => 'Modification de la notice : ',
        'Title_crud_new' => 'Création d\'une nouvelle notice',
        'Lbl_notices_title' => 'Titre :',
        'Lbl_notices_label' => 'Libellé :',
        'Lbl_notices_reference' => 'Code :',
        'Lbl_notices_info' => 'Info',
        'Lbl_notices_image' => 'Image :',
        'Lbl_notices_description' => 'Description :',
        'Lbl_notices_comp' => 'Complément',
        'Lbl_notices_comp_image' => 'Image :',
        'Lbl_notices_comp_description' => 'Description :',
      ),
    ),
    'nodes' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Noeuds',
        'header_list_1' => 'Id',
        'header_list_2' => 'Code',
        'header_list_3' => 'Titre',
        'header_list_4' => 'libellé',
        'filter_list_id' => 'Id : ',
        'filter_list_reference' => 'Code noeud : ',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' noeuds trouvés',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression du noeud',
        'Lbl_delete' => 'Voulez-vous supprimer ce noeud ?',
        'Title_crud_edit' => 'Modification du noeud : ',
        'Title_crud_new' => 'Création d\'un nouveau noeud',
        'Lbl_nodes_contentInfo' => 'Info',
        'Lbl_nodes_contentQuestion' => 'question',
        'Lbl_nodes_nodeFrom' => 'Parent :',
        'Lbl_nodes_diagram_id' => 'Arborescence :',
        'Lbl_nodes_root' => 'Racine :',
        'Lbl_nodes_root_1' => 'Non',
        'Lbl_nodes_root_2' => 'Oui',
        'Lbl_nodes_slide_id' => 'Slide :',
        'Lbl_nodes_slide_label' => 'Libellé :',
        'Lbl_nodes_slide_title' => 'Titre slide :',
        'Lbl_nodes_reference' => 'Code :',
        'Lbl_nodes_information' => 'Information :',
        'Lbl_nodes_slide_image' => 'Image :',
        'Lbl_nodes_slide_image_display' => 'Afficher l\'image :',
        'Lbl_nodes_slide_image_display_1' => 'Non',
        'Lbl_nodes_slide_image_display_2' => 'Oui',
        'Lbl_nodes_slide_description' => 'Description :',
        'Lbl_nodes_question_id' => 'Question :',
        'Lbl_nodes_question_label' => 'Libellé Question :',
        'Lbl_nodes_question' => 'Question :',
        'Lbl_nodes_question_description' => 'Détail Question :',
        'Title_to' => 'Cible : ',
        'Title_action' => 'Quelle action sur le noeud souhaitez-vous ?',
        'Bt_order' => 'Déplacer',
        'Bt_move' => 'Attacher à',
        'Bt_copy' => 'Copier sous',
      ),
    ),
    'questions' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Questions',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'libellé',
        'header_list_1' => 'Code',
        'header_list_2' => 'Libellé',
        'filter_list_reference' => 'Code : ',
        'filter_list_label' => 'Libellé : ',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' questions trouvées',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression de la question',
        'Lbl_delete' => 'Voulez-vous supprimer cette question ?',
        'Title_crud_edit' => 'Modification de la question : ',
        'Title_crud_new' => 'Création d\'une nouvelle question',
        'Lbl_questions_label' => 'Libellé :',
        'Lbl_questions_title' => 'Titre :',
        'Lbl_questions_reference' => 'Code :',
        'Lbl_questions_info' => 'Info',
        'Lbl_questions_image' => 'Image :',
        'Lbl_questions_description' => 'Description :',
        'Lbl_questions_comp' => 'Complément',
        'Lbl_questions_comp_image' => 'Image :',
        'Lbl_questions_comp_description' => 'Description :',
      ),
    ),
    'links' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Liens',
        'header_list_1' => 'Source',
        'header_list_2' => 'Noeud source',
        'header_list_3' => 'Cible',
        'header_list_4' => 'Noeud cible',
        'filter_list_nodeFrom_id' => 'Code noeud source : ',
        'filter_list_nodeTo_id' => 'Code noeud cible : ',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' liens trouvés',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression du lien',
        'Lbl_delete' => 'Voulez-vous supprimer ce lien ?',
        'Title_crud_edit' => 'Modification du lien : ',
        'Title_crud_new' => 'Création d\'un nouveau lien',
        'Lbl_links_nodeFrom_id' => 'Noeud source :',
        'Lbl_links_nodeTo_id' => 'Noeud cible :',
        'Lbl_links_nodeFrom' => 'Noeud source :',
        'Lbl_links_nodeTo' => 'Noeud cible :',
        'Lbl_links_response' => 'Réponse :',
        'Lbl_links_description' => '',
      ),
    ),
    'results' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Résultats',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'Nom',
        'header_list_1' => 'Catégorie',
        'header_list_2' => 'Nom',
        'header_list_3' => 'Type',
        'header_list_4' => 'Libellé',
        'header_list_5' => 'Affiché',
        'header_list_6' => 'Ligne',
        'filter_list_category_id' => 'Catégorie : ',
        'filter_list_type_id' => 'Type : ',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' résultats trouvés',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression du résultat',
        'Lbl_delete' => 'Voulez-vous supprimer ce résultat ?',
        'Title_crud_edit' => 'Modification du résultat : ',
        'Title_crud_new' => 'Création d\'un nouveau résultat',
        'Lbl_results_name' => 'Nom :',
        'Lbl_results_type_id' => 'Type :',
        'Lbl_results_category_id' => 'Catégorie :',
        'Lbl_results_label' => 'Libellé :',
        'Lbl_results_display_func' => 'Condition :',
        'Lbl_results_sequence' => 'Ordre :',
        'Lbl_results_mandatory' => 'Obligatoire :',
        'Lbl_results_mandatory_1' => 'Non',
        'Lbl_results_mandatory_2' => 'Oui',
        'Lbl_results_nodisplay' => 'Affichage :',
        'Lbl_results_nodisplay_1' => 'Oui',
        'Lbl_results_nodisplay_2' => 'Non',
        'Lbl_results_line' => 'Même ligne :',
        'Lbl_results_line_1' => 'Non',
        'Lbl_results_line_2' => 'Oui',
        'Lbl_results_formula' => 'Formule :',
        'Lbl_results_description' => '',
      ),
    ),
    'resultcategories' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Catégories de résultats',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'Nom',
        'header_list_1' => 'Nom',
        'header_list_2' => 'Libellé',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' catégories trouvées',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression de la catégorie de résultat',
        'Lbl_delete' => 'Voulez-vous supprimer cette catégorie de résultat ?',
        'Title_crud_edit' => 'Modification de la catégorie de résultat : ',
        'Title_crud_new' => 'Création d\'une nouvelle catégorie de résultat',
        'Lbl_resultcategories_name' => 'Nom :',
        'Lbl_resultcategories_label' => 'Libellé :',
        'Lbl_resultcategories_description' => '',
      ),
    ),
    'resulttypes' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Types de resultats',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'Code',
        'header_list_1' => 'Code',
        'header_list_2' => 'Libellé',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' types trouvés',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression du type de resultat',
        'Lbl_delete' => 'Voulez-vous supprimer ce type de resultat ?',
        'Title_crud_edit' => 'Modification du type de resultat : ',
        'Title_crud_new' => 'Création d\'un nouveau type de resultat',
        'Lbl_resulttypes_code' => 'Code :',
        'Lbl_resulttypes_label' => 'Libellé :',
      ),
    ),
    'slides' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Slides',
        'header_list_1' => 'code',
        'header_list_2' => 'Type',
        'header_list_3' => 'libellé',
        'filter_list_reference' => 'Code : ',
        'filter_list_label' => 'Libellé : ',
        'filter_list_type_id' => 'Type : ',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' slides trouvés',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression du slide',
        'Lbl_delete' => 'Voulez-vous supprimer ce slide ?',
        'Title_crud_edit' => 'Modification du slide : ',
        'Title_crud_new' => 'Création d\'un nouveau slide',
        'Lbl_slides_label' => 'Libellé :',
        'Lbl_slides_title' => 'Titre :',
        'Lbl_slides_reference' => 'Code :',
        'Lbl_slides_contentInfo' => 'Info',
        'Lbl_slides_contentNotice' => 'Notice',
        'Lbl_slides_contentVariable' => 'Variables',
        'Lbl_slides_contentResult' => 'Résultats',
        'Lbl_slides_contentLink' => 'Liens',
        'Lbl_slides_image' => 'Image :',
        'Lbl_slides_image_display' => 'Afficher l\'image :',
        'Lbl_slides_image_display_1' => 'Non',
        'Lbl_slides_image_display_2' => 'Oui',
        'Lbl_slides_description' => 'Description :',
        'Lbl_slides_notice_id' => 'Notice :',
        'Lbl_slides_notice_label' => 'Libellé notice :',
        'Lbl_slides_notice_title' => 'Titre notice :',
        'Lbl_slides_notice_image' => 'Image notice :',
        'Lbl_slides_notice_description' => '',
        'Lbl_slides_information' => 'Saisie infos :',
        'Lbl_slides_information_1' => 'Non',
        'Lbl_slides_information_2' => 'Oui',
        'Lbl_slides_variable_list' => 'Variables :',
        'Lbl_slides_variable_1_list' => 'Variables :',
        'Lbl_slides_variable_contentid' => 'Contenu variable :',
        'Lbl_slides_variable_label' => 'Libellé variable :',
        'Lbl_slides_variable_title' => 'Titre variable :',
        'Lbl_slides_variable_image' => 'Image variable :',
        'Lbl_slides_variable_description' => '',
        'Lbl_slides_result_list' => 'Résultats :',
        'Lbl_slides_result_1_list' => 'Résultats :',
        'Lbl_slides_result_contentid' => 'Contenu résultat :',
        'Lbl_slides_result_label' => 'Libellé résultat :',
        'Lbl_slides_result_title' => 'Titre résultat :',
        'Lbl_slides_result_image' => 'Image résultat :',
        'Lbl_slides_result_description' => '',
        'Lbl_slides_process_id' => 'Processus associé :',
        'Lbl_slides_link_list' => 'Slides associés',
      ),
    ),
    'tables' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'tables',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'Nom',
        'header_list_1' => 'Nom',
        'header_list_2' => 'Type',
        'header_list_3' => 'Libellé',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' tables trouvées',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression de la table',
        'Lbl_delete' => 'Voulez-vous supprimer cette table ?',
        'Title_crud_edit' => 'Modification de la table : ',
        'Title_crud_new' => 'Création d\'une nouvelle table',
        'Lbl_tables_name' => 'Nom :',
        'Lbl_tables_type_id' => 'Type :',
        'Lbl_tables_label' => 'Libellé :',
        'Lbl_tables_col1_field' => 'Dimension 1 :',
        'Lbl_tables_col1_byrange' => 'Par palier :',
        'Lbl_tables_col1_byrange_1' => 'Non',
        'Lbl_tables_col1_byrange_2' => 'Oui',
        'Lbl_tables_col2_field' => 'Dimension 2 :',
        'Lbl_tables_col2_byrange' => 'Par palier :',
        'Lbl_tables_col2_byrange_1' => 'Non',
        'Lbl_tables_col2_byrange_2' => 'Oui',
        'Lbl_tables_col3_field' => 'Dimension 3 :',
        'Lbl_tables_col3_byrange' => 'Par palier :',
        'Lbl_tables_col3_byrange_1' => 'Non',
        'Lbl_tables_col3_byrange_2' => 'Oui',
        'Lbl_tables_table_data' => '',
        'Datagrid_tables_col1_min' => 'Dimension 1',
        'Datagrid_tables_col1_max' => 'Max Dim. 1',
        'Datagrid_tables_col2_min' => 'Dimension 2',
        'Datagrid_tables_col2_max' => 'Max Dim. 2',
        'Datagrid_tables_col3_min' => 'Dimension 3',
        'Datagrid_tables_col3_max' => 'Max Dim. 3',
        'Datagrid_tables_value' => 'Valeur',
      ),
    ),
    'tabletypes' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Types de grilles',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'Code',
        'header_list_1' => 'Code',
        'header_list_2' => 'Libellé',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' types trouvés',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression du type de grille',
        'Lbl_delete' => 'Voulez-vous supprimer ce type de grille ?',
        'Title_crud_edit' => 'Modification du type de grille : ',
        'Title_crud_new' => 'Création d\'un nouveau type de grille',
        'Lbl_tabletypes_code' => 'Code :',
        'Lbl_tabletypes_label' => 'Libellé :',
      ),
    ),
    'variables' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Variables',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'Nom',
        'header_list_1' => 'Catégorie',
        'header_list_2' => 'Nom',
        'header_list_3' => 'Type',
        'header_list_4' => 'Libellé',
        'header_list_5' => 'Affiché',
        'header_list_6' => 'Ligne',
        'filter_list_category_id' => 'Catégorie : ',
        'filter_list_type_id' => 'Type : ',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' variables trouvées',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression de la variable',
        'Lbl_delete' => 'Voulez-vous supprimer cette variable ?',
        'Title_crud_edit' => 'Modification de la variable : ',
        'Title_crud_new' => 'Création d\'une nouvelle variable',
        'Lbl_variables_name' => 'Nom :',
        'Lbl_variables_type_id' => 'Type :',
        'Lbl_variables_category_id' => 'Catégorie :',
        'Lbl_variables_label' => 'Libellé :',
        'Lbl_variables_no_label' => 'Sans libellé :',
        'Lbl_variables_no_label_1' => 'Non',
        'Lbl_variables_no_label_2' => 'Oui',
        'Lbl_variables_display_func' => 'Condition :',
        'Lbl_variables_sequence' => 'Ordre :',
        'Lbl_variables_mandatory' => 'Obligatoire :',
        'Lbl_variables_mandatory_1' => 'Non',
        'Lbl_variables_mandatory_2' => 'Oui',
        'Lbl_variables_nodisplay' => 'Affichage :',
        'Lbl_variables_nodisplay_1' => 'Oui',
        'Lbl_variables_nodisplay_2' => 'Non',
        'Lbl_variables_size' => 'Taille :',
        'Lbl_variables_format' => 'Format :',
        'Lbl_variables_value' => 'Valeurs :',
        'Lbl_variables_object_items' => 'Eléments :',
        'Lbl_variables_nolabel' => 'Sans Nom d\'éléments :',
        'Lbl_variables_nolabel_1' => 'Non',
        'Lbl_variables_nolabel_2' => 'Oui',
        'Lbl_variables_description' => 'Description',
        'Lbl_variables_line' => 'Même ligne :',
        'Lbl_variables_line_1' => 'Non',
        'Lbl_variables_line_2' => 'Oui',
      ),
    ),
    'variablecategories' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Catégories de variables',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'Nom',
        'header_list_1' => 'Nom',
        'header_list_2' => 'Libellé',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' catégories trouvées',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression de la catégorie de variable',
        'Lbl_delete' => 'Voulez-vous supprimer cette catégorie de variable ?',
        'Title_crud_edit' => 'Modification de la catégorie de variable : ',
        'Title_crud_new' => 'Création d\'une nouvelle catégorie de variable',
        'Lbl_variablecategories_name' => 'Nom :',
        'Lbl_variablecategories_label' => 'Libellé :',
        'Lbl_variablecategories_description' => '',
      ),
    ),
    'variabletypes' => 
    array (
      'vars' => 
      array (
        'Title_list' => 'Types de variables',
        'Lbl_list_orderby_0' => 'Identifiant',
        'Lbl_list_orderby_1' => 'Code',
        'header_list_1' => 'Code',
        'header_list_2' => 'Libellé',
        'txt_list_caption_count_begin' => '',
        'txt_list_caption_count_end' => ' types trouvés',
        'txt_list_caption_search_begin' => ' pour le filtre \'',
        'txt_list_caption_search_end' => '\'',
        'Title_delete' => 'Suppression du type de variable',
        'Lbl_delete' => 'Voulez-vous supprimer ce type de variable ?',
        'Title_crud_edit' => 'Modification du type de variable : ',
        'Title_crud_new' => 'Création d\'un nouveau type de variable',
        'Lbl_variabletypes_code' => 'Code :',
        'Lbl_variabletypes_label' => 'Libellé :',
      ),
    ),
  ),
  'vars' => 
  array (
    'Txt_app_title' => 'Power Arbo',
    'menu_home_text' => 'Power Arbo',
    'Txt_home' => 'Acceuil',
    'Txt_connect' => 'Connexion',
    'Lbl_login_login' => 'Login',
    'Txt_login_login_placeholder' => 'Utilisateur',
    'Txt_login_password_placeholder' => 'Mot de passe',
    'Txt_return_page' => 'Retour',
    'Title_visualisation_slides' => 'Visualisation des slides',
    'Title_visualisation_diagrams' => 'Visualisation des arborescences de situation',
    'Title_visualisation_processes' => 'Visualisation des procédures',
    'Title_visualisation_variables' => 'Visualisation des variables',
    'Title_visualisation_results' => 'Visualisation des résultats',
    'Label_visualisation_slides' => 'Visualisation :',
    'Label_visualisation_slides_simple' => 'Simple',
    'Label_visualisation_slides_sheets' => 'Onglets',
    'Label_visualisation_diagrams' => 'Situation :',
    'Label_visualisation_processes' => 'Procédure :',
    'Label_domain' => 'Domaine :',
    'Title_select_domain' => 'Choisissez un domaine',
    'currency' => 'Devise',
    'date' => 'Date',
    'display' => 'Display',
    'integer' => 'Entier',
    'list_integer' => 'Liste d\'entiers',
    'list_string' => 'Liste de chaîne de caractères',
    'mail' => 'Email',
    'number' => 'Nombre',
    'object' => 'Objet',
    'process' => 'Arborescence de procédure',
    'string' => 'Chaîne de caractères',
    'standard' => 'Arborescence de situation',
  ),
));
}
}
